name = "marks-new"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-09-27"

kv_namespaces = [
  { binding = "BOOKMARK", preview_id = "", id = "7ae9a43c54f0460e986dde276fe443b5" }
]

[site]
entry-point = "./"
bucket = "./public"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[secrets]
# NAME
# PASS
